const $=s=>document.querySelector(s);
async function api(url, options={}) {const r=await fetch(url,options); const data=await r.json(); if(!r.ok) throw new Error(typeof data.detail==='string'?data.detail:JSON.stringify(data.detail));return data;}
const post=(url,data)=>api(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
function el(tag,text,cls){const e=document.createElement(tag);if(text!=null)e.textContent=text;if(cls)e.className=cls;return e;}
let status;
async function load(){try{status=await api('/demo/status');$('#connection').textContent='● 本機服務運作中';$('#mode').textContent=status.llm_ready?'LLM 已設定':'本地語意搜尋';$('#ask').disabled=!status.llm_ready;$('#embed-info').textContent=`${status.embedding_mode} / ${status.embedding_model}`;const s=await api('/demo/settings');$('#base-url').value=s.base_url;$('#model-name').value=s.model;$('#graph').checked=s.graph_enabled;$('#api-key').placeholder=s.has_api_key?'已儲存金鑰；留白保留':'輸入 API key／存取密碼';}catch(e){$('#connection').textContent='服務尚未就緒';$('#message').textContent=e.message;}}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.hidden=x.id!==b.dataset.tab);document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x===b));if(b.dataset.tab==='files')files();});
document.querySelectorAll('[data-query]').forEach(b=>b.onclick=()=>{$('#query').value=b.dataset.query;search(false);});
function renderChunks(chunks){$('#results').replaceChildren();$('#result-count').textContent=`${chunks.length} 個證據片段`;if(!chunks.length){$('#results').append(el('p','沒有找到相關片段。請確認文件索引已完成，或換一種描述。','empty'));return;}chunks.forEach((c,i)=>{const card=el('article',null,'card');const head=el('div',null,'card-head');const title=el('h3');const source=c.source;if(source){const a=el('a',`${i+1}. ${source.name}`);a.href=source.url;a.target='_blank';a.rel='noopener';title.append(a);}else title.textContent=`${i+1}. ${c.file_path||'文件片段'}`;head.append(title,el('span',source?.location||'來源片段','badge'));card.append(head,el('div',c.content||c.text||'','excerpt'));if(source?.images?.length){const images=el('div',null,'images');source.images.forEach(url=>{const a=el('a');a.href=source.url;a.target='_blank';a.rel='noopener';const img=el('img');img.src=url;img.alt=`${source.name} ${source.location} 原圖`;img.loading='lazy';a.append(img);images.append(a);});card.append(images,el('p','圖片為此來源區段的原圖；不代表模型已理解圖片。','muted'));}$('#results').append(card);});}
async function search(answer){const query=$('#query').value.trim();if(query.length<2){$('#message').textContent='請至少輸入兩個字。';return;}$('#submit').disabled=true;$('#ask').disabled=true;$('#message').textContent='正在檢索研究證據…';$('#answer').hidden=true;try{const body={query,limit:6,mode:$('#retrieval').value};const result=await post('/demo/search',body);renderChunks(result.data?.chunks||[]);$('#message').textContent='';if(answer){$('#message').textContent='正在依據證據產生回答…';const r=await post('/demo/ask',body);$('#answer').textContent=r.response||JSON.stringify(r);if(r.references?.length)renderChunks(r.references.map(x=>({...x,content:Array.isArray(x.content)?x.content.join(String.fromCharCode(10,10)):x.content})));$('#answer').hidden=false;$('#message').textContent='';}}catch(e){$('#message').textContent=e.message;}finally{$('#submit').disabled=false;$('#ask').disabled=!status?.llm_ready;}}
$('#submit').onclick=()=>search(false);$('#ask').onclick=()=>search(true);$('#query').onkeydown=e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey))search(false);};
async function files(){try{const items=await api('/demo/sources');$('#file-list').replaceChildren();if(!items.length)$('#file-list').append(el('p','尚無文件。請選擇文件並匯入。','empty'));const names={processed:'已建立索引',queued:'等待處理',processing:'處理中',failed:'處理失敗','index-removed':'索引已移除，原檔保留','index-missing':'查無索引','no-indexable-text':'沒有可索引文字'};for(const x of items){const card=el('div',null,'card');const a=el('a',x.name);a.href=`/demo/source.html?id=${x.id}`;a.target='_blank';a.rel='noopener';card.append(a,el('p',`${names[x.state]||x.state} · ${new Date(x.created_at).toLocaleString()}`,'muted'));(x.warnings||[]).forEach(w=>card.append(el('p',w,'muted')));if(x.state==='processed'||x.state==='failed'){const remove=el('button','移除搜尋索引（保留原檔）','secondary');remove.onclick=async()=>{if(!confirm(`移除 ${x.name} 的搜尋索引？原檔與圖片會保留，可下載後重新匯入。`))return;remove.disabled=true;try{const r=await api(`/demo/sources/${x.id}/index`,{method:'DELETE'});$('#upload-message').textContent=r.message;await files();}catch(e){$('#upload-message').textContent=e.message;remove.disabled=false;}};card.append(remove);}$('#file-list').append(card);}}catch(e){$('#upload-message').textContent=e.message;}}
$('#refresh').onclick=files;$('#import').onclick=async()=>{const selected=[...$('#upload').files];if(!selected.length)return;$('#import').disabled=true;try{for(const file of selected){$('#upload-message').textContent=`正在解析並匯入 ${file.name}…`;const form=new FormData();form.append('file',file);const result=await api('/demo/upload',{method:'POST',body:form});$('#upload-message').textContent=`${result.name}：${result.state}\n${result.warnings.join('\n')}\n匯入後請等待向量索引完成，再進行搜尋。`;}await files();}catch(e){$('#upload-message').textContent=e.message;}finally{$('#import').disabled=false;}};
$('#settings-form').onsubmit=async e=>{e.preventDefault();try{const result=await post('/demo/settings',{base_url:$('#base-url').value,model:$('#model-name').value,api_key:$('#api-key').value,graph_enabled:$('#graph').checked});$('#settings-message').textContent=result.message;$('#api-key').value='';}catch(e){$('#settings-message').textContent=e.message;}};load();
